apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: jenkins-devopsgalaxy-cert
  namespace: kidangel
spec:
  secretName: jenkins-devopsgalaxy-cert
  dnsNames:
  - jenkins.devopsgalaxy.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - jenkins.devopsgalaxy.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer