# command kubectl create secret tls kizcloud-cert --key kizcloud-key.pem --cert kizcloud.pem --namespace=kidangel
apiVersion: v1
data:
  tls.crt: secrets/kizcloud-chain.pem
  tls.key: secrets/kizcloud-key.pem
kind: Secret
metadata:
  name: kizcloud-cert
  namespace: kidangel
type: Opaque