apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: wordpress-devopsgalaxy-cert
  namespace: kidangel
spec:
  secretName: wordpress-devopsgalaxy-cert
  dnsNames:
  - wordpress.devopsgalaxy.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - wordpress.devopsgalaxy.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer