apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-disk-data
  namespace: kidangel
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: premium-managed-disk-storageclass
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-disk-extensions
  namespace: kidangel
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: premium-managed-disk-storageclass
  resources:
    requests:
      storage: 2Gi