apiVersion: v1
kind: ServiceAccount
metadata:
  name: kidangel-svc-account
  namespace: kidangel
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:azure-cloud-provider-kidangel
  namespace: kidangel
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: system:azure-cloud-provider
subjects:
  - kind: ServiceAccount
    name: kidangel-svc-account
    namespace: kidangel
