apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: share-premium-data-disk
  namespace: kidangel
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: premium-managed-disk-storageclass
  resources:
    requests:
      storage: 128Gi