apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: share-standard-data-disk
  namespace: kidangel
  labels:
    app: sonarqube
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-managed-disk-storageclass
  resources:
    requests:
      storage: 128Gi