apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-db-data
  namespace: kidangel
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: wordpress-storage-class
  resources:
    requests:
      storage: 30Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  namespace: kidangel
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: wordpress-storage-class
  resources:
    requests:
      storage: 30Gi