apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-upload-data
  namespace: kidangel
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: wordpress-upload-storage-class
  resources:
    requests:
      storage: 10Gi