apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus3-default-disk-data
  namespace: kidangel
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 32Gi