apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus3-disk-data
  namespace: kidangel
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: premium-managed-disk-storageclass
  resources:
    requests:
      storage: 8Gi