apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJzb25jdCIsInBhc3N3b3JkIjoiU29uQ1RANDgxOTkxIiwiZW1haWwiOiJzb250aGFuaC5jYW9AaG90bWFpbC5jb20iLCJhdXRoIjoiYzI5dVkzUTZVMjl1UTFSQU5EZ3hPVGt4In19fQ==
kind: Secret
metadata:
  namespace: kidangel
  creationTimestamp: null
  name: sonctdockerhub
type: kubernetes.io/dockerconfigjson