kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: wordpress-upload-storage-class
provisioner: kubernetes.io/azure-file
reclaimPolicy: Retain
mountOptions:
  - dir_mode=0777
  - file_mode=0766
  - uid=999
  - gid=999
parameters:
  skuName: Standard_LRS
  storageAccount: kidk8sdata